export const EN_MESSAGES = {
  "app.loading": "Loading Owner Mode...",
  "locale.en": "English",
  "locale.zh": "中文",
  "locale.switcher.aria_label": "Select language",
  "login.kicker": "SupeRISE Owner Mode",
  "login.title": "Take control of the Agent credit wallet",
  "login.description":
    "This is a local console for the Owner. The Agent never handles private keys, while the Owner can inspect state, sign messages, transfer funds, adjust limits, and perform recovery actions when needed.",
  "login.notice.first_boot":
    "The first-run default credential is written to a local notice file. Rotate it as soon as you log in.",
  "brand.owner_console": "Owner Console",
  "login.auth_label": "Owner Authentication",
  "login.console_title": "Sign in to the console",
  "login.password_placeholder": "Enter the Owner password",
  "login.submit": "Enter Owner Console",
  "header.title": "Privileged operations console",
  "header.refresh": "Refresh",
  "header.logout": "Log out",
  "menu.overview": "Overview",
  "menu.wallet": "Wallet",
  "menu.transfers": "Transfers",
  "menu.signing": "Signing",
  "menu.address_book": "Address book",
  "menu.limits": "Limits",
  "menu.security": "Security & credential",
  "menu.audit": "Audit log",
  "section.overview.title": "Overview",
  "section.wallet.title": "Wallet",
  "section.transfers.title": "Transfers",
  "section.signing.title": "Signing",
  "section.address_book.title": "Address book",
  "section.limits.title": "Limits",
  "section.security.title": "Security & credential",
  "section.audit.title": "Audit log",
  "section.overview.description":
    "A takeover-focused summary view that combines balances, risk reminders, and the current wallet state.",
  "section.wallet.description":
    "Review the address, public key, and balances of the current wallet by chain without expanding transaction details by default.",
  "section.transfers.description":
    "Send transfers by asset and choose either a raw address or an address-book contact name as the target.",
  "section.signing.description":
    "Sign on-chain messages and inspect the signing address, public key, and resulting signature.",
  "section.address_book.description":
    "Manage shared contacts, filter them, edit entries, and perform exact address lookups.",
  "section.limits.description":
    "Review and update per-asset daily, weekly, and monthly limits plus current usage.",
  "section.security.description":
    "Rotate the Owner credential, import or recover the wallet, and export the private key for high-risk workflows.",
  "section.audit.description": "Review the latest Owner audit records.",
  "credential.unknown": "Credential status unknown",
  "credential.pending_rotation": "Default credential pending rotation",
  "credential.active": "Credential rotated",
  "wallet.status.ACTIVE": "Active",
  "wallet.status.EMPTY": "Empty",
  "wallet.status.unknown": "Unknown",
  "wallet.source.AUTO_GENERATED": "Auto-generated",
  "wallet.source.IMPORTED": "Imported",
  "wallet.source.UNKNOWN": "Unknown",
  "address_book.state.ready": "Ready",
  "address_book.state.empty": "Empty",
  "tab.nervos": "Nervos",
  "tab.ethereum": "Ethereum",
  "common.none": "-",
  "common.unlimited": "Unlimited",
  "common.cancel": "Cancel",
  "common.query": "Query",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.create": "Create",
  "common.copy_result": "Result",
  "common.base_value": "Base unit value: {value}",
  "common.page_item.contacts": "contacts",
  "common.page_item.records": "records",
  "common.page_item.items": "items",
  "overview.alert.owner_bypass":
    "Owner operations bypass the Agent-side asset limits. Reconfirm every transfer, export, and import before you proceed.",
  "overview.stat.wallet_fingerprint": "Wallet fingerprint",
  "overview.stat.wallet_status": "Wallet status",
  "overview.stat.address_book_contacts": "Address-book contacts",
  "overview.stat.audit_records": "Audit records",
  "overview.card.balance_summary": "On-chain balance summary",
  "overview.card.live_tag": "Live view",
  "overview.card.console_status": "Console status",
  "overview.card.current_wallet_source": "Current wallet source",
  "overview.card.configured_limit_assets": "Configured limit assets",
  "overview.card.address_book_availability": "Address book availability",
  "overview.card.limit_progress": "Limit configuration {percent}%",
  "overview.card.risk_notices": "Risk notices",
  "overview.card.high_privilege": "Owner high privilege",
  "overview.card.quick_summary": "Quick summary",
  "overview.summary.nervos_address": "Nervos address",
  "overview.summary.ethereum_address": "Ethereum address",
  "overview.summary.latest_audit_count": "Latest audit count: {count} records",
  "overview.summary.contact_count": "Contact count: {count} contacts",
  "risk_notice.sign_transfer":
    "Signing and transfers always use the current wallet directly. Verify the chain and asset type first.",
  "risk_notice.owner_limit_bypass":
    "Agent asset limits are enforced only on the server side. Manual Owner operations are not blocked by those limits.",
  "risk_notice.import_export":
    "Importing a private key replaces the current wallet. Exporting it gives the Owner direct wallet control.",
  "risk_notice.jwt_expiry":
    "The Owner access token is valid for one hour by default. Sign in again after it expires.",
  "wallet.card.current_wallet": "Current wallet",
  "wallet.field.fingerprint": "Fingerprint",
  "wallet.field.status": "Status",
  "wallet.field.source": "Source",
  "wallet.card.nervos_balance": "Nervos / CKB",
  "wallet.card.ethereum_balance": "Ethereum",
  "wallet.balance.label": "{asset} balance",
  "wallet.field.address": "Address",
  "wallet.field.public_key": "Public key",
  "transfers.card.title": "{asset} transfer",
  "transfers.target_type": "Target type",
  "transfers.target_type.address": "Raw address",
  "transfers.target_type.contact_name": "Contact name",
  "transfers.target_address": "Target address",
  "transfers.contact_name": "Contact name",
  "transfers.amount": "Amount ({description})",
  "transfers.submit": "Submit {asset} transfer",
  "transfers.description.CKB": "Minimum unit integer, 100000000 = 1 CKB",
  "transfers.description.ETH": "Minimum unit integer, 1000000000000000000 = 1 ETH",
  "transfers.description.USDT": "Minimum unit integer, 1000000 = 1 USDT",
  "transfers.description.USDC": "Minimum unit integer, 1000000 = 1 USDC",
  "signing.card.title": "{chain} message signing",
  "signing.message": "Message",
  "signing.encoding": "Encoding",
  "signing.submit": "Submit signature",
  "signing.result.address": "Signing address",
  "signing.result.public_key": "Public key",
  "signing.result.signature": "Signature",
  "address_book.card.contacts": "Contact list",
  "address_book.filter_placeholder": "Filter by name or note",
  "address_book.new_contact": "New contact",
  "address_book.table.contact": "Contact",
  "address_book.table.nervos": "Nervos",
  "address_book.table.ethereum": "Ethereum",
  "address_book.table.note": "Note",
  "address_book.table.actions": "Actions",
  "address_book.empty": "No contacts yet",
  "address_book.lookup.title": "Address lookup",
  "address_book.lookup.placeholder": "Enter a CKB or Ethereum address",
  "address_book.lookup.matched": "Matched{chainSuffix}",
  "address_book.lookup.not_matched": "No contact matched",
  "address_book.lookup.none": "No contacts matched this address",
  "address_book.modal.edit_title": "Edit contact",
  "address_book.modal.create_title": "Create contact",
  "address_book.modal.delete_contact": "Delete contact",
  "address_book.modal.save_contact": "Save contact",
  "address_book.modal.create_contact": "Create contact",
  "address_book.field.name": "Contact name",
  "address_book.field.nervos_address": "Nervos address",
  "address_book.field.ethereum_address": "Ethereum address",
  "address_book.field.note": "Note",
  "limits.window.daily_limit": "Daily limit",
  "limits.window.weekly_limit": "Weekly limit",
  "limits.window.monthly_limit": "Monthly limit",
  "limits.window.day": "Day",
  "limits.window.week": "Week",
  "limits.window.month": "Month",
  "limits.window.card": "{label} window",
  "limits.usage.configured": "Configured: {amount}",
  "limits.usage.consumed": "Consumed: {amount}",
  "limits.usage.reserved": "Reserved: {amount}",
  "limits.usage.effective_used": "Effective used: {amount}",
  "limits.usage.remaining": "Remaining: {amount}",
  "limits.usage.resets_at": "Reset at: {value}",
  "limits.placeholder": "Leave empty for unlimited",
  "security.card.rotate": "Credential rotation",
  "security.field.current_password": "Current password",
  "security.field.new_password": "New password",
  "security.submit.rotate": "Update credential",
  "security.card.import": "Import recovery",
  "security.alert.import":
    "Importing a private key replaces the current wallet immediately. Use it only for recovery scenarios.",
  "security.field.private_key": "Private key",
  "security.field.confirm_replace": "Confirm replacement",
  "security.submit.import": "Import and replace wallet",
  "security.card.export": "High-risk export",
  "security.alert.export":
    "Exporting the private key gives the Owner direct wallet control.",
  "security.submit.export": "Export private key",
  "audit.table.action": "Action",
  "audit.table.role": "Role",
  "audit.table.result": "Result",
  "audit.table.time": "Time",
  "audit.empty": "No audit records yet",
  "audit.role.AGENT": "Agent",
  "audit.role.OWNER": "Owner",
  "audit.role.SYSTEM": "System",
  "audit.result.SUCCESS": "Success",
  "audit.result.FAILED": "Failed",
  "audit.action.wallet.bootstrap": "Wallet bootstrap",
  "audit.action.owner_credential.bootstrap": "Owner credential bootstrap",
  "audit.action.address_book.create": "Address-book contact created",
  "audit.action.address_book.update": "Address-book contact updated",
  "audit.action.address_book.delete": "Address-book contact deleted",
  "audit.action.nervos.sign_message": "Nervos message signed",
  "audit.action.nervos.transfer_ckb": "CKB transfer submitted",
  "audit.action.ethereum.sign_message": "Ethereum message signed",
  "audit.action.ethereum.transfer_eth": "ETH transfer submitted",
  "audit.action.ethereum.transfer_usdt": "USDT transfer submitted",
  "audit.action.ethereum.transfer_usdc": "USDC transfer submitted",
  "audit.action.owner.login": "Owner login",
  "audit.action.owner.rotate_credential": "Owner credential rotated",
  "audit.action.wallet.import": "Wallet imported",
  "audit.action.wallet.export": "Wallet exported",
  "audit.action.vault.rotate_kek": "KEK rotated",
  "audit.action.owner.asset_limit.update": "Asset limit updated",
  "audit.action.transfer.settlement_confirmed": "Transfer settlement confirmed",
  "audit.action.transfer.settlement_failed": "Transfer settlement failed",
  "toast.refresh.success": "Data refreshed.",
  "toast.session_expired": "Your session expired. Sign in again.",
  "toast.load_failed": "Failed to load Owner Mode.",
  "toast.chain_refresh_failed": "Failed to refresh chain data.",
  "toast.action_failed": "The operation failed.",
  "toast.login.pending_rotation":
    "Signed in. The default credential is still active, so rotate it as soon as possible.",
  "toast.login.success": "Signed in to Owner Mode.",
  "toast.logout.success": "Signed out of Owner Mode.",
  "toast.credential_rotated":
    "The Owner credential was updated. Sign in again with the new password.",
  "toast.sign.success": "{chain} message signing completed.",
  "toast.transfer.success": "{asset} transfer submitted: {operationId} -> {target}",
  "toast.contact.updated": "Contact updated: {name}",
  "toast.contact.created": "Contact created: {name}",
  "toast.contact.delete_requires_selection": "Select a contact first.",
  "toast.contact.deleted": "Contact deleted: {name}",
  "toast.address_lookup.success": "Address lookup completed.",
  "toast.address_lookup.not_matched": "The address did not match any contact.",
  "toast.limit.not_found": "The selected limit configuration was not found.",
  "toast.limit.saved": "{asset} limit saved.",
  "toast.import.requires_confirmation":
    "Confirm that the import should replace the current wallet first.",
  "toast.wallet.imported": "The wallet was imported and replaced successfully.",
  "toast.wallet.exported":
    "The private key was exported. Handle it as a high-risk secret.",
  "modal.import.title": "Import and replace the current wallet?",
  "modal.import.content":
    "This operation directly replaces the only wallet. Use it only during recovery.",
  "modal.import.confirm": "Import wallet",
  "modal.export.title": "Export the private key?",
  "modal.export.content":
    "After export, the Owner has direct wallet control. Treat the exported private key as a high-risk secret.",
  "modal.export.confirm": "Export private key",
  "amount.hint.display":
    "Up to {decimals} decimal places are supported. The value is converted to {baseUnit} automatically.",
  "amount.hint.scaled":
    "Up to {decimals} decimal places are supported. The value is converted to {baseUnit} automatically.",
  "amount.hint.base": "Enter {baseUnit} directly. Decimal places are not allowed.",
  "amount.error.required": "Enter an amount.",
  "amount.error.invalid_number": "The amount must be a valid number.",
  "amount.error.base_no_decimal": "{baseUnit} does not support decimal input.",
  "amount.error.max_decimals": "{unit} supports up to {decimals} decimal places.",
  "amount.error.invalid_format": "The amount format is invalid.",
  "amount.error.non_negative": "The amount must be non-negative.",
  "amount.error.positive_required": "The amount must be greater than 0.",
  "amount.error.precise_conversion":
    "The amount cannot be converted to the base unit precisely.",
  "error.generic": "Something went wrong. Try again.",
  "error.request_failed": "The request failed. Try again.",
  "error.server_non_json": "The server returned a non-JSON response.",
  "error.server_invalid_json": "The server returned invalid JSON.",
  "error.validation": "The request payload is invalid.",
  "error.auth": "Authentication failed. Sign in again.",
  "error.wallet_not_found": "The wallet is not initialized yet.",
  "error.wallet_import_failed": "Failed to import the wallet.",
  "error.wallet_export_failed": "Failed to export the wallet.",
  "error.vault": "The secure vault operation failed.",
  "error.database_unavailable": "The database is currently unavailable.",
  "error.chain_unavailable": "The chain service is currently unavailable.",
  "error.insufficient_balance": "The wallet balance is insufficient for this action.",
  "error.transfer_build_failed": "Failed to build the transfer transaction.",
  "error.transfer_broadcast_failed": "Failed to broadcast the transfer transaction.",
  "error.sign_message_failed": "Failed to sign the message.",
  "error.asset_limit_exceeded": "{asset} {window} limit exceeded.",
  "error.address_book.contact_not_found": "The contact was not found.",
  "error.address_book.contact_exists": "A contact with the same name already exists.",
  "error.address_book.contact_empty":
    "At least one valid field is required to create or update a contact.",
  "error.address_book.invalid_nervos_address": "The Nervos address is invalid.",
  "error.address_book.invalid_ethereum_address": "The Ethereum address is invalid.",
  "error.address_book.address_not_found_for_chain":
    "The selected contact does not have an address for this chain.",
} as const;

export type TranslationKey = keyof typeof EN_MESSAGES;
export type TranslationCatalog = Record<TranslationKey, string>;

export const ZH_MESSAGES: TranslationCatalog = {
  "app.loading": "正在加载 Owner Mode...",
  "locale.en": "English",
  "locale.zh": "中文",
  "locale.switcher.aria_label": "选择语言",
  "login.kicker": "SupeRISE Owner Mode",
  "login.title": "接管 Agent 信用钱包",
  "login.description":
    "这是一个面向 Owner 的本地控制台。Agent 不接触私钥，而 Owner 可以在必要时查看状态、签名、转账、调整限额并执行恢复操作。",
  "login.notice.first_boot":
    "首次启动的默认凭证会写入本机通知文件，登录后请尽快轮换。",
  "brand.owner_console": "Owner 控制台",
  "login.auth_label": "Owner 身份认证",
  "login.console_title": "登录控制台",
  "login.password_placeholder": "输入 Owner 密码",
  "login.submit": "进入 Owner 控制台",
  "header.title": "高权限操作台",
  "header.refresh": "刷新",
  "header.logout": "退出",
  "menu.overview": "概览",
  "menu.wallet": "钱包状态",
  "menu.transfers": "转账",
  "menu.signing": "签名",
  "menu.address_book": "地址簿",
  "menu.limits": "限额管理",
  "menu.security": "安全与凭证",
  "menu.audit": "审计日志",
  "section.overview.title": "概览",
  "section.wallet.title": "钱包状态",
  "section.transfers.title": "转账",
  "section.signing.title": "签名",
  "section.address_book.title": "地址簿",
  "section.limits.title": "限额管理",
  "section.security.title": "安全与凭证",
  "section.audit.title": "审计日志",
  "section.overview.description":
    "面向人工接管场景的总览视图，聚合余额、风险提示和当前钱包状态。",
  "section.wallet.description":
    "按链查看当前唯一钱包的地址、公钥与余额，不默认铺开交易细节。",
  "section.transfers.description":
    "按资产拆分转账操作，支持直接输入地址或地址簿联系人名称。",
  "section.signing.description": "执行链上消息签名，返回签名地址、公钥与签名结果。",
  "section.address_book.description":
    "维护共享联系人，支持筛选、编辑和精确地址反查。",
  "section.limits.description":
    "查看并调整按资产维度的日、周、月限额配置与使用情况。",
  "section.security.description":
    "处理凭证轮换、钱包导入恢复和高风险私钥导出。",
  "section.audit.description": "查看最新 Owner 操作审计记录。",
  "credential.unknown": "凭证状态未知",
  "credential.pending_rotation": "默认凭证待轮换",
  "credential.active": "凭证已轮换",
  "wallet.status.ACTIVE": "已激活",
  "wallet.status.EMPTY": "空",
  "wallet.status.unknown": "未知",
  "wallet.source.AUTO_GENERATED": "自动生成",
  "wallet.source.IMPORTED": "导入恢复",
  "wallet.source.UNKNOWN": "未知",
  "address_book.state.ready": "已就绪",
  "address_book.state.empty": "空",
  "tab.nervos": "Nervos",
  "tab.ethereum": "Ethereum",
  "common.none": "-",
  "common.unlimited": "不限额",
  "common.cancel": "取消",
  "common.query": "查询",
  "common.save": "保存",
  "common.delete": "删除",
  "common.edit": "编辑",
  "common.create": "创建",
  "common.copy_result": "结果",
  "common.base_value": "基础单位值：{value}",
  "common.page_item.contacts": "个",
  "common.page_item.records": "条",
  "common.page_item.items": "项",
  "overview.alert.owner_bypass":
    "Owner 操作不受 Agent 侧限额拦截，请在执行转账、导出和导入前再次确认。",
  "overview.stat.wallet_fingerprint": "钱包指纹",
  "overview.stat.wallet_status": "钱包状态",
  "overview.stat.address_book_contacts": "地址簿联系人",
  "overview.stat.audit_records": "审计记录",
  "overview.card.balance_summary": "链上余额概览",
  "overview.card.live_tag": "实时视图",
  "overview.card.console_status": "控制台状态",
  "overview.card.current_wallet_source": "当前钱包来源",
  "overview.card.configured_limit_assets": "已配置限额资产",
  "overview.card.address_book_availability": "地址簿可用性",
  "overview.card.limit_progress": "限额配置 {percent}%",
  "overview.card.risk_notices": "风险提示",
  "overview.card.high_privilege": "Owner 高权限",
  "overview.card.quick_summary": "快速摘要",
  "overview.summary.nervos_address": "Nervos 地址",
  "overview.summary.ethereum_address": "Ethereum 地址",
  "overview.summary.latest_audit_count": "最新审计数量：{count} 条",
  "overview.summary.contact_count": "联系人数量：{count} 个",
  "risk_notice.sign_transfer":
    "签名和转账都会直接使用当前唯一钱包，请先确认链与资产类型。",
  "risk_notice.owner_limit_bypass":
    "Agent 的币种限额只在 server 侧生效，Owner 手动操作不会被这套限额阻塞。",
  "risk_notice.import_export":
    "导入私钥会替换当前钱包；导出私钥后，Owner 将直接掌握钱包控制权。",
  "risk_notice.jwt_expiry":
    "JWT 访问令牌默认 1 小时有效，过期后需要重新登录。",
  "wallet.card.current_wallet": "当前钱包",
  "wallet.field.fingerprint": "钱包指纹",
  "wallet.field.status": "状态",
  "wallet.field.source": "来源",
  "wallet.card.nervos_balance": "Nervos / CKB",
  "wallet.card.ethereum_balance": "Ethereum",
  "wallet.balance.label": "{asset} 余额",
  "wallet.field.address": "地址",
  "wallet.field.public_key": "公钥",
  "transfers.card.title": "{asset} 转账",
  "transfers.target_type": "目标类型",
  "transfers.target_type.address": "原始地址",
  "transfers.target_type.contact_name": "联系人名称",
  "transfers.target_address": "目标地址",
  "transfers.contact_name": "联系人名称",
  "transfers.amount": "数量（{description}）",
  "transfers.submit": "提交 {asset} 转账",
  "transfers.description.CKB": "最小单位整数，100000000 = 1 CKB",
  "transfers.description.ETH": "最小单位整数，1000000000000000000 = 1 ETH",
  "transfers.description.USDT": "最小单位整数，1000000 = 1 USDT",
  "transfers.description.USDC": "最小单位整数，1000000 = 1 USDC",
  "signing.card.title": "{chain} 消息签名",
  "signing.message": "消息",
  "signing.encoding": "编码",
  "signing.submit": "提交签名",
  "signing.result.address": "签名地址",
  "signing.result.public_key": "公钥",
  "signing.result.signature": "签名结果",
  "address_book.card.contacts": "联系人列表",
  "address_book.filter_placeholder": "按名称或备注筛选",
  "address_book.new_contact": "新建联系人",
  "address_book.table.contact": "联系人",
  "address_book.table.nervos": "Nervos",
  "address_book.table.ethereum": "Ethereum",
  "address_book.table.note": "备注",
  "address_book.table.actions": "操作",
  "address_book.empty": "暂无联系人",
  "address_book.lookup.title": "地址反查",
  "address_book.lookup.placeholder": "输入 CKB / Ethereum 地址",
  "address_book.lookup.matched": "匹配成功{chainSuffix}",
  "address_book.lookup.not_matched": "未匹配到联系人",
  "address_book.lookup.none": "当前没有命中联系人",
  "address_book.modal.edit_title": "编辑联系人",
  "address_book.modal.create_title": "新建联系人",
  "address_book.modal.delete_contact": "删除联系人",
  "address_book.modal.save_contact": "保存联系人",
  "address_book.modal.create_contact": "创建联系人",
  "address_book.field.name": "联系人名称",
  "address_book.field.nervos_address": "Nervos 地址",
  "address_book.field.ethereum_address": "Ethereum 地址",
  "address_book.field.note": "备注",
  "limits.window.daily_limit": "日限额",
  "limits.window.weekly_limit": "周限额",
  "limits.window.monthly_limit": "月限额",
  "limits.window.day": "日",
  "limits.window.week": "周",
  "limits.window.month": "月",
  "limits.window.card": "{label}窗口",
  "limits.usage.configured": "配置：{amount}",
  "limits.usage.consumed": "已消耗：{amount}",
  "limits.usage.reserved": "已预占：{amount}",
  "limits.usage.effective_used": "有效已用：{amount}",
  "limits.usage.remaining": "剩余：{amount}",
  "limits.usage.resets_at": "重置：{value}",
  "limits.placeholder": "留空表示不限额",
  "security.card.rotate": "凭证轮换",
  "security.field.current_password": "当前密码",
  "security.field.new_password": "新密码",
  "security.submit.rotate": "更新凭证",
  "security.card.import": "导入恢复",
  "security.alert.import":
    "导入会直接替换当前唯一钱包，仅建议在恢复场景下使用。",
  "security.field.private_key": "私钥",
  "security.field.confirm_replace": "确认替换",
  "security.submit.import": "导入并替换钱包",
  "security.card.export": "高风险导出",
  "security.alert.export": "导出私钥后，Owner 将直接掌握钱包控制权。",
  "security.submit.export": "导出私钥",
  "audit.table.action": "动作",
  "audit.table.role": "角色",
  "audit.table.result": "结果",
  "audit.table.time": "时间",
  "audit.empty": "暂无审计记录",
  "audit.role.AGENT": "Agent",
  "audit.role.OWNER": "Owner",
  "audit.role.SYSTEM": "System",
  "audit.result.SUCCESS": "成功",
  "audit.result.FAILED": "失败",
  "audit.action.wallet.bootstrap": "钱包初始化",
  "audit.action.owner_credential.bootstrap": "Owner 凭证初始化",
  "audit.action.address_book.create": "地址簿联系人已创建",
  "audit.action.address_book.update": "地址簿联系人已更新",
  "audit.action.address_book.delete": "地址簿联系人已删除",
  "audit.action.nervos.sign_message": "Nervos 消息签名",
  "audit.action.nervos.transfer_ckb": "CKB 转账已提交",
  "audit.action.ethereum.sign_message": "Ethereum 消息签名",
  "audit.action.ethereum.transfer_eth": "ETH 转账已提交",
  "audit.action.ethereum.transfer_usdt": "USDT 转账已提交",
  "audit.action.ethereum.transfer_usdc": "USDC 转账已提交",
  "audit.action.owner.login": "Owner 登录",
  "audit.action.owner.rotate_credential": "Owner 凭证已轮换",
  "audit.action.wallet.import": "钱包已导入",
  "audit.action.wallet.export": "钱包已导出",
  "audit.action.vault.rotate_kek": "KEK 已轮换",
  "audit.action.owner.asset_limit.update": "资产限额已更新",
  "audit.action.transfer.settlement_confirmed": "转账结算已确认",
  "audit.action.transfer.settlement_failed": "转账结算失败",
  "toast.refresh.success": "数据已刷新。",
  "toast.session_expired": "登录状态已过期，请重新登录。",
  "toast.load_failed": "Owner Mode 加载失败。",
  "toast.chain_refresh_failed": "链上数据刷新失败。",
  "toast.action_failed": "操作失败。",
  "toast.login.pending_rotation": "已登录。当前仍是默认凭证，请尽快轮换。",
  "toast.login.success": "已登录 Owner Mode。",
  "toast.logout.success": "已退出 Owner Mode。",
  "toast.credential_rotated": "Owner 凭证已更新，请使用新密码重新登录。",
  "toast.sign.success": "{chain} 消息签名完成。",
  "toast.transfer.success": "{asset} 转账已提交：{operationId} -> {target}",
  "toast.contact.updated": "联系人已更新：{name}",
  "toast.contact.created": "联系人已创建：{name}",
  "toast.contact.delete_requires_selection": "请先选择一个联系人。",
  "toast.contact.deleted": "联系人已删除：{name}",
  "toast.address_lookup.success": "地址反查完成。",
  "toast.address_lookup.not_matched": "地址未匹配到联系人。",
  "toast.limit.not_found": "未找到对应的限额配置。",
  "toast.limit.saved": "{asset} 限额已保存。",
  "toast.import.requires_confirmation": "请先确认导入会替换当前唯一钱包。",
  "toast.wallet.imported": "钱包已导入并替换当前钱包。",
  "toast.wallet.exported": "私钥已导出。请按高风险动作处理。",
  "modal.import.title": "确认导入并替换当前钱包？",
  "modal.import.content": "该操作会直接替换当前唯一钱包，仅建议在恢复场景中使用。",
  "modal.import.confirm": "确认导入",
  "modal.export.title": "确认导出私钥？",
  "modal.export.content":
    "导出后 Owner 将直接掌握钱包控制权，请按高风险动作处理导出的私钥。",
  "modal.export.confirm": "确认导出",
  "amount.hint.display": "支持最多 {decimals} 位小数，提交时会自动转换为 {baseUnit}。",
  "amount.hint.scaled": "支持最多 {decimals} 位小数，提交时会自动转换为 {baseUnit}。",
  "amount.hint.base": "直接输入基础单位 {baseUnit}，不允许小数。",
  "amount.error.required": "请输入金额。",
  "amount.error.invalid_number": "金额必须是合法数字。",
  "amount.error.base_no_decimal": "{baseUnit} 输入不支持小数。",
  "amount.error.max_decimals": "{unit} 最多支持 {decimals} 位小数。",
  "amount.error.invalid_format": "金额格式无效。",
  "amount.error.non_negative": "金额必须是非负数。",
  "amount.error.positive_required": "金额必须大于 0。",
  "amount.error.precise_conversion": "金额无法精确转换为基础单位。",
  "error.generic": "发生未知错误，请稍后重试。",
  "error.request_failed": "请求失败，请稍后重试。",
  "error.server_non_json": "服务端返回了非 JSON 响应。",
  "error.server_invalid_json": "服务端返回了无效 JSON。",
  "error.validation": "请求参数不合法。",
  "error.auth": "鉴权失败，请重新登录。",
  "error.wallet_not_found": "当前还没有可用钱包。",
  "error.wallet_import_failed": "钱包导入失败。",
  "error.wallet_export_failed": "钱包导出失败。",
  "error.vault": "安全密钥仓库操作失败。",
  "error.database_unavailable": "数据库当前不可用。",
  "error.chain_unavailable": "链服务当前不可用。",
  "error.insufficient_balance": "钱包余额不足，无法完成当前操作。",
  "error.transfer_build_failed": "转账交易构建失败。",
  "error.transfer_broadcast_failed": "转账交易广播失败。",
  "error.sign_message_failed": "消息签名失败。",
  "error.asset_limit_exceeded": "{asset} 的{window}限额已超出。",
  "error.address_book.contact_not_found": "未找到对应联系人。",
  "error.address_book.contact_exists": "同名联系人已存在。",
  "error.address_book.contact_empty": "创建或更新联系人时，至少需要提供一个有效字段。",
  "error.address_book.invalid_nervos_address": "Nervos 地址无效。",
  "error.address_book.invalid_ethereum_address": "Ethereum 地址无效。",
  "error.address_book.address_not_found_for_chain": "该联系人未配置当前链对应的地址。",
};

export const TRANSLATION_CATALOGS = {
  en: EN_MESSAGES,
  zh: ZH_MESSAGES,
} as const;
