export const MCP_TOOL_NAMES = [
  "wallet.current",
  "wallet.operation_status",
  "address_book.list",
  "address_book.search",
  "address_book.lookup_by_address",
  "address_book.get",
  "address_book.get_all",
  "address_book.create",
  "address_book.update",
  "address_book.delete",
  "nervos.identity",
  "nervos.balance.ckb",
  "nervos.sign_message",
  "nervos.transfer.ckb",
  "nervos.tx_status",
  "ethereum.identity",
  "ethereum.balance.eth",
  "ethereum.balance.usdt",
  "ethereum.balance.usdc",
  "ethereum.sign_message",
  "ethereum.transfer.eth",
  "ethereum.transfer.usdt",
  "ethereum.transfer.usdc",
  "ethereum.tx_status",
] as const;

export type McpToolName = (typeof MCP_TOOL_NAMES)[number];
